# Default initial positions for fr3's ros2_control fake system

initial_positions:
  fr3_joint1: 0.0
  fr3_joint2: 0.0
  fr3_joint3: 0.0
  fr3_joint4: -1.596950
  fr3_joint5: 0.0
  fr3_joint6: 2.530700
  fr3_joint7: 0.0